### ISSUE TITLE
programatic "before" example doesn't work

### ISSUE THREAD

**Issue by jaredh159** [matken11235/slack-cleaner2#1]
in the README.md it says we can do this:

```yml
before: "$(date -v -1m '+%Y%m%d')"  # You can use bash style command.
```

But I found that this did _not_ work.  First of all the `-v` date offset, is for BSD `date` which works on a Mac, but not on Ubuntu.

Second, even after correcting the date syntax, it wasn't getting passed through to the command correctly inside the Docker container. I tried a bunch of things, but I finally got it working by doing this:

```yml
# .github/workflows/slack-cleaner.yml

name: Slack Cleaner
on:
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ::set-env name=BEFORE::$(date -d '-5 days' '+%Y%m%d') # <-- set env
      - uses: matken11235/slack-cleaner@v1
        with:
          group: mychannel
          before: ${{ env.BEFORE }} # <-- use env
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_LEGACY_TOKEN }
```

I'd be happy to PR the change to the readme, if you'd like.
